version: '3.0'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hublasales
    ports:
      - "5432:5432"
  # backend:
  #   build: ./backend/
  #   environment:
  #     DatabaseServer: "db"
  #     DatabasePort: "5432"
  #     DatabaseUser: "postgres"
  #     DatabasePassword: "admin"
  #     DatabaseName: "hublasales"
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - db
  # frontend:
  #   build: ./frontend/
  #   ports:
  #     - "5173:3000"