version: '3.0'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hublasales
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: backend/src/Hubla.Sales.API/Dockerfile
    ports:
      - "5095:80"
    depends_on:
      - db
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend